### ISSUE TITLE
Question: Why not use native JS features?

### ISSUE THREAD

**Issue by anampartho** [BYOJS/storage#3]
Hi @getify! Great work here. I just wanted to know your thought process in one of your design decisions.

I was going through the `keys` function on https://github.com/BYOJS/storage/blob/main/src/adapter.local-storage.js#L62-L68 and I saw that you used an approach using for loop:

```javascript
function keys() {
	var storeKeys = [];
	for (let i = 0; i < window.localStorage.length; i++) {
		storeKeys.push(window.localStorage.key(i));
	}
	return storeKeys;
}
```

For some reason I was expecting something like:

```javascript
function keys() {
	return Object.keys(window.localStorage);
}
```

# So the question: Why choose for loop over `Object.keys` or `Object.entries`?

**Comment by getify** [comment]
Hmmm... I've never seen this before. As far as I can tell, it's [not documented behavior on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Storage) nor even in [the HTML spec](https://html.spec.whatwg.org/multipage/webstorage.html#storage).

The fact that the API exposes the `key()` function, seems like evidence that this was the intended way to enumerate its contents. I wonder if browsers decided on their own to make them enumerable through `Object.keys()` / `Object.entries()` / `Object.values()`?

I would want to find evidence of the intentional design of that behavior before I'd want to rely on it.

**Comment by anampartho** [comment]
Every `Document` has a `local storage holder` which is either `null` or a `Storage` object. This `Storage` object defines the interface for the `localStorage` and `sessionStorage`.

When we try to get the `localStorage` by doing `window.localStorage` it gives us the `Storage` object which is stored inside the `local storage holder` and by default this is a simple key value store and is [similar to an `Object`](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#basic_concepts).

So, if we check if `localStorage` is an `instanceof` `Object` we can see it returns true:

```js
window.localStorage instanceof Object; // true
```

Being an object, all its keys are enumerable and when we use `Object.keys`, all it does:

1. Let obj be ? [ToObject](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-toobject)(O).
2. Let keyList be ? [EnumerableOwnProperties](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-enumerableownproperties)(obj, key).
3. Return [CreateArrayFromList](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-createarrayfromlist)(keyList).

So, only takes the `EnumerableOwnProperties` and ignores the inherited properties like `getItem`, `setItem` etc.

No matter how we set the data into the `localStorage` it is enumerable by default:

```js
window.localStorage['my key 1'] = 'my value 1';
window.localStorage.setItem('my key 2') = 'my value 2';

Object.keys(window.localStorage); // ['my key 2', 'my key 1']
```

It seems to be the default behavior because the [Storage Interface](https://html.spec.whatwg.org/multipage/webstorage.html#storage) mentions that both `storage.setItem(key, value)` and `storage[key] = value` does the same thing.

But, getting the item seems different. When we try to retrieve an item from `localStorage` using `getItem`, it returns `null` if the item is not present and when we use the `.` notation or `[]` notation to get an item which is not present, gives `undefined`. This can be clear by looking at the [algorithm `getItem` uses](https://html.spec.whatwg.org/multipage/webstorage.html#dom-storage-getitem):

1. If [this](https://webidl.spec.whatwg.org/#this)'s [map](https://html.spec.whatwg.org/multipage/webstorage.html#concept-storage-map)[key] does not [exist](https://infra.spec.whatwg.org/#map-exists), then return null.
2. Return [this](https://webidl.spec.whatwg.org/#this)'s [map](https://html.spec.whatwg.org/multipage/webstorage.html#concept-storage-map)[key].

And when we use the `.` or `[]` notation, as the key is not present in the object itself, we get `undefined`.

[An specific algorithms is also used for the `key` method where the keys of the internal maps are created and then the key at `index` is returned]()https://html.spec.whatwg.org/multipage/webstorage.html#dom-storage-key:
1. If index is greater than or equal to [this](https://webidl.spec.whatwg.org/#this)'s [map](https://html.spec.whatwg.org/multipage/webstorage.html#concept-storage-map)'s [size](https://infra.spec.whatwg.org/#map-size), then return null.
2. Let keys be the result of running [get the keys](https://infra.spec.whatwg.org/#map-getting-the-keys) on [this](https://webidl.spec.whatwg.org/#this)'s [map](https://html.spec.whatwg.org/multipage/webstorage.html#concept-storage-map).
3. Return keys[index].

Now, both the `for` loop method and `Object.keys` does the same thing, but it seems everything boils down to performance and preference. That would be something interesting to look into as well.

@getify sorry about the long comment. This was an interesting look into the topic, thanks for the intriguing reply which led me to do some basic research in this topic!

Good luck!

**Comment by getify** [comment]
It's not "just like any other plain object", it's a special object, with a specifically designed and documented API provided by the browser (not even JS). That API is how *you're supposed to* interact with it.

I've never seen any real world code that's using it "as just a plain object".  MDN doesn't mention any of this (at least as far as I could see), and I didn't even know it was possible. I think that hints at how outside of the mainstream the approach is.

Even though it seems it's *possible*, I don't think there's sufficient justification to deviate from the API and use it like a normal object. No significant upside as far as I can tell, and possible nuanced differences to chase down (like `null` vs `undefined` on retrieving a value, as you mentioned).

**Comment by anampartho** [comment]
It was a good few hours while I was at it. Answers the main question I asked for now. Cheers!

**Comment by getify** [comment]
Also, it seems it has some nuanced behavior if you set a property called "length" into Storage, since the object has its own default magical `length` property/getter (similar to arrays).

```js
// doesn't work
window.localStorage.length = 42;

// works, but now shadows/overrides the automatic `length` property/getter
window.localStorage.setItem("length",42);
```

**Comment by getify** [comment]
Appreciate the feedback and looking into it via research. I definitely learned something here. :)
