### ISSUE TITLE
setMany(), getMany(), removeMany()

### ISSUE THREAD

**Issue by getify** [BYOJS/storage#5]
add feature to set/get/remove multiple keys/values at a time.

thx @wesbos for the idea!

**Comment by MuaviyaImran** [comment]
@getify  Hi, I hope all is well with you. Would you kindly assign me this problem? I'd want to help.

**Comment by MuaviyaImran** [comment]
@getify I have a question do we need to support all types of structures like
`setMany({ 'key1': 'string', 'key2': 'object', 'key3':'array' })` and so on..

**Comment by getify** [comment]
I think we should start with arrays:

```js
setMany([ [ "prop1", "val1" ], [ "prop2", "val2" ] ])  // [ true, true ] 

getMany([ "prop1", "prop2" ])  // {"prop1": "val1", "prop2": "val2" }

removeMany([ "prop1", "prop2" ]) // [ true, true ] 
```

**Comment by getify** [comment]
let's actually expose these as:

```js
set.many(..)
get.many(..)
remove.many(..)
```

**Comment by MuaviyaImran** [comment]
@getify - I have implemented getMany, setMany and removeMany with all types of structures

- setMany({ 'key1': 'string', 'key2': 'object', 'key3':'array' })
- getMany(['string', 'obj', 'array'])
- removeMany(['string', 'obj','array'])

They are working in idb, cookies, local-storage, and session-storage with test cases
Now i am implementing in opfs

**Comment by getify** [comment]
getMany() and removeMany() should be accepting prop names, not values (as indicated by your comment).

**Comment by MuaviyaImran** [comment]
Yeah they will receive key names by parameters and return actual values

**Comment by getify** [comment]
FWIW, here's what I was envisioning for how to approach the implementation:

```js
function setMany(data) {
   if (data != null && typeof data == "object" && !Array.isArray(data)) {
      data = [ ...Object.entries(data) ];
   }
   return Promise.all(
      data.values.map(([ prop, val ]) => set(prop,val))
   );
}
```

In other words, ideally these utilities are just "helpers" that call the corresponding `set()` / `get()` / `remove()` utilities, and are therefore not requiring specific logic for any one adapter type.

Perhaps if they are indeed just generalized logic, we can then include them once, in a separate `many.js` helpers file, that is imported by each adapter, and then re-exported on each adapter's interface, like:

```js
import { getMany, setMany, removeMany } from "./many.js";
get.many = getMany;
set.many = setMany;
remove.many = removeMany;

// ..

export {
   // ..
   get,
   set,
   remove,
   // ..
};
var publicAPI = {
   // ..
   get,
   set,
   remove,
   // ..
};
```

**Comment by MuaviyaImran** [comment]
Sure i got the point.
